"""Per-unit parameter schemas served by ``GET /unit-types`` so the GUI can
build typed parameter forms (number / int / boolean / select / string / json)
with units, defaults, ranges, help text and conditional applicability.

GENERATED from the engine unit ops (build_param_schemas.py); the ENGINE
remains the source of truth - every unit validates its own params in
``solve``/``_read_params`` and raises a typed error. A param entry mirrors
the engine key and may carry: label, type, default, required, unit (SI), dim
(for unit-system conversion), min/max, options, requires {param: value},
complex (list/dict value), help.
"""
from __future__ import annotations

PARAM_SCHEMAS: dict[str, list[dict]] = {'Absorber': [{'name': 'n_stages',
               'label': 'Number of theoretical stages',
               'type': 'int',
               'required': True,
               'min': 1,
               'help': 'Theoretical stages (no condenser/reboiler). Required, >= 1.'},
              {'name': 'P',
               'label': 'Top-stage pressure',
               'type': 'number',
               'unit': 'Pa',
               'dim': 'pressure',
               'min': 0,
               'help': 'Pressure at the top stage (Pa). Default: gas feed pressure.'},
              {'name': 'dP_stage',
               'label': 'Linear pressure rise per stage',
               'type': 'number',
               'default': 0,
               'unit': 'Pa',
               'dim': 'pressure',
               'min': 0,
               'help': 'Linear pressure rise per stage going down (Pa). Default: 0 (uniform '
                       'pressure).'},
              {'name': 'method',
               'label': 'MESH solver method',
               'type': 'select',
               'default': 'sum_rates',
               'options': ['sum_rates', 'naphtali_sandholm'],
               'help': 'MESH solver: sum_rates (default, Burningham-Otto, fast) or '
                       'naphtali_sandholm (simultaneous-correction, robust fallback for '
                       'limit-cycling like amine regenerators). sum_rates does not support '
                       'condenser_T/reboiler_T/reboiler_duty.'},
              {'name': 'murphree',
               'label': 'Murphree vapor stage efficiency',
               'type': 'json',
               'complex': True,
               'help': 'Optional Murphree vapor stage efficiency for kinetically limited mass '
                       'transfer. A scalar (all components) or {component: E} dict (0 < E <= 1); '
                       'default 1.0 (equilibrium). E.g. CO2 ~ 0.15 with tertiary amine. '
                       'sum_rates only; not supported in naphtali_sandholm.'},
              {'name': 'condenser_T',
               'label': 'Partial condenser temperature',
               'type': 'number',
               'unit': 'K',
               'dim': 'temperature',
               'min': 0,
               'requires': {'method': 'naphtali_sandholm'},
               'help': 'Optional partial (reflux) condenser temperature at the top stage (K). '
                       'Stage 0 becomes the condenser pinned to this temperature; condensables '
                       'drop out as internal reflux, drying the overhead (natural for amine '
                       'regenerators). Requires method=naphtali_sandholm and n_stages >= 2. '
                       'design[condenser_duty] (negative) closes the overall energy balance.'},
              {'name': 'reboiler_T',
               'label': 'Reboiler temperature',
               'type': 'number',
               'unit': 'K',
               'dim': 'temperature',
               'min': 0,
               'requires': {'method': 'naphtali_sandholm'},
               'help': 'Optional reboiler temperature at the bottom stage (K). The bottom stage '
                       'boils up the stripping vapour internally, pinned to this temperature; '
                       'gas_in becomes optional. Requires method=naphtali_sandholm and n_stages '
                       '>= 2 (or >= 3 if condenser_T also set). design[reboiler_duty] (positive) '
                       'is the output.'},
              {'name': 'reboiler_duty',
               'label': 'Reboiler heat input',
               'type': 'number',
               'unit': 'W',
               'dim': 'power',
               'min': 0,
               'requires': {'method': 'naphtali_sandholm'},
               'help': 'Optional reboiler heat input (W, positive). The alternative reboiler '
                       'spec to reboiler_T: sets the heat input instead of pinning temperature; '
                       'keeps the stage energy balance intact (better conditioned). Robust for '
                       'amine regenerators paired with condenser_T (closed water loop, no open '
                       'steam). Requires method=naphtali_sandholm, n_stages >= 2, and water in '
                       'the system (for the warm-start proxy).'},
              {'name': 'max_iter',
               'label': 'Iteration cap',
               'type': 'int',
               'default': 120,
               'min': 1,
               'help': 'Iteration cap for the MESH solver (default 120). Raise if convergence is '
                       'slow on difficult specs.'}],
 'AirCooler': [{'name': 'T_out',
                'label': 'Outlet temperature',
                'type': 'number',
                'required': True,
                'unit': 'K',
                'dim': 'temperature',
                'help': 'Process outlet temperature; must be >= t_air_in + approach to cool '
                        'ambient air'},
               {'name': 't_air_in',
                'label': 'Ambient air inlet temperature',
                'type': 'number',
                'default': 308.15,
                'unit': 'K',
                'dim': 'temperature',
                'help': 'Design ambient air inlet temperature; default 308.15 K (35 C)'},
               {'name': 'approach',
                'label': 'Minimum approach temperature',
                'type': 'number',
                'default': 10,
                'unit': 'K',
                'dim': 'temperature',
                'min': 0,
                'help': 'Minimum process-outlet-to-air-inlet temperature approach; enforces '
                        'T_out >= t_air_in + approach'},
               {'name': 'dP',
                'label': 'Tube-side pressure drop',
                'type': 'number',
                'default': 0,
                'unit': 'Pa',
                'dim': 'pressure',
                'min': 0,
                'help': 'Pressure drop across the tubes on the process side'}],
 'BaghouseFilter': [{'name': 'solids',
                     'label': 'Solid component(s) to separate',
                     'type': 'string',
                     'required': True,
                     'help': 'Component id (str) or list of ids of the dust component(s) to '
                             'collect; must exist in flowsheet'},
                    {'name': 'efficiency',
                     'label': 'Overall collection efficiency',
                     'type': 'number',
                     'default': 0.999,
                     'min': 0,
                     'max': 1,
                     'help': 'Bulk collection efficiency; well-run baghouses routinely exceed '
                             '99.9%'},
                    {'name': 'face_velocity',
                     'label': 'Gas face velocity',
                     'type': 'number',
                     'default': 0.01,
                     'unit': 'm/s',
                     'min': 0,
                     'help': 'Superficial gas velocity through cloth (air-to-cloth ratio); ~2 '
                             'ft/min woven fabric, 0.025-0.06 m/s pulse-jet felts'},
                    {'name': 'S_E',
                     'label': 'Clean fabric drag',
                     'type': 'number',
                     'default': 25000,
                     'unit': 'Pa/(m/s)',
                     'min': 0,
                     'help': 'Conditioned-fabric drag coefficient (~0.5 in H2O/(ft/min), '
                             'mid-range); pressure drop of clean bag at unit face velocity'},
                    {'name': 'K2',
                     'label': 'Dust cake resistance coefficient',
                     'type': 'number',
                     'default': 50000,
                     'unit': 'Pa·s·m/kg',
                     'min': 0,
                     'help': 'Specific dust-cake resistance (~5 in H2O/(ft/min)/(lb/ft²), '
                             'mid-range); filter-drag model coefficient'},
                    {'name': 'dP_max',
                     'label': 'Bag-cleaning trigger pressure drop',
                     'type': 'number',
                     'default': 2000,
                     'unit': 'Pa',
                     'dim': 'pressure',
                     'min': 0,
                     'help': 'Maximum allowable pressure drop before bag cleaning; also the '
                             'gas-side dP applied to gas_out (conservative ceiling)'},
                    {'name': 'bag_diameter_m',
                     'label': 'Bag diameter',
                     'type': 'number',
                     'default': 0.15,
                     'unit': 'm',
                     'min': 0,
                     'help': 'Per-bag diameter for bag count suggestion; typical pulse-jet bags'},
                    {'name': 'bag_length_m',
                     'label': 'Bag length',
                     'type': 'number',
                     'default': 3,
                     'unit': 'm',
                     'min': 0,
                     'help': 'Per-bag length for bag count suggestion; typical pulse-jet bags'}],
 'Balance': [{'name': 'n_inlets',
              'label': 'Number of inlet streams',
              'type': 'int',
              'default': 1,
              'min': 1,
              'help': 'Number of inlet material streams. Must be at least 1; port names are in1, '
                      'in2, ..., inN.'},
             {'name': 'mode',
              'label': 'Balance mode',
              'type': 'select',
              'default': 'mole',
              'options': ['mole', 'mass', 'heat', 'mole_heat', 'mass_heat'],
              'help': 'Conservation type: mole (per-component molar flow), mass (total mass '
                      'only), heat (enthalpy flow as energy outlet), mole_heat (component moles '
                      '+ enthalpy, PH-flashed), mass_heat (total mass + enthalpy, PH-flashed).'},
             {'name': 'z_out',
              'label': 'Outlet composition',
              'type': 'json',
              'required': True,
              'requires': {'mode': 'mass,mass_heat'},
              'complex': True,
              'help': 'Outlet mole-fraction composition as {component: fraction}. Required for '
                      'mass and mass_heat modes; must sum to >0 (will be normalized).'},
             {'name': 'P',
              'label': 'Outlet pressure',
              'type': 'number',
              'unit': 'Pa',
              'dim': 'pressure',
              'min': 0,
              'requires': {'mode': 'mole_heat,mass_heat'},
              'help': 'Outlet pressure for PH flash in mole_heat and mass_heat modes. If '
                      'omitted, defaults to the minimum inlet pressure.'}],
 'CSTR': [{'name': 'V',
           'label': 'Reactor volume',
           'type': 'number',
           'required': True,
           'unit': 'm³',
           'min': 0,
           'help': 'Reactor volume in cubic meters; must be positive.'},
          {'name': 'reactions',
           'label': 'Kinetic reactions',
           'type': 'json',
           'required': True,
           'complex': True,
           'editor': 'reaction',
           'editor_opts': {'kind': 'kinetic', 'multiple': True,
                           'conversion': False, 'key_required': True,
                           'reversible': True},
           'help': 'List of kinetic reaction dicts, each with stoich, key, k0, Ea, orders, '
                   'optional k0_rev/Ea_rev/orders_rev.'},
          {'name': 'T',
           'label': 'Isothermal temperature',
           'type': 'number',
           'unit': 'K',
           'dim': 'temperature',
           'min': 50,
           'help': 'Operating temperature in Kelvin. If present, reactor is isothermal with duty '
                   'to maintain it. Absent: adiabatic (outlet T from enthalpy balance).'},
          {'name': 'dP',
           'label': 'Pressure drop',
           'type': 'number',
           'default': 0,
           'unit': 'Pa',
           'dim': 'pressure',
           'min': 0,
           'help': 'Pressure drop across the reactor in Pa, applied at outlet. Kinetics '
                   'evaluated at outlet pressure.'}],
 'ClausReactor': [{'name': 'T',
                   'label': 'Outlet temperature',
                   'type': 'number',
                   'unit': 'K',
                   'dim': 'temperature',
                   'min': 273.15,
                   'max': 2000,
                   'help': 'Outlet temperature. Omit for adiabatic thermal furnace (flame '
                           'temperature predicted); set for isothermal catalytic converter.'},
                  {'name': 'P',
                   'label': 'Outlet pressure',
                   'type': 'number',
                   'unit': 'Pa',
                   'dim': 'pressure',
                   'min': 0.1,
                   'max': 10000000,
                   'help': 'Outlet pressure. Defaults to inlet (in1) pressure if omitted.'},
                  {'name': 'dP',
                   'label': 'Pressure drop',
                   'type': 'number',
                   'default': 0,
                   'unit': 'Pa',
                   'dim': 'pressure',
                   'min': 0,
                   'max': 1000000,
                   'help': 'Pressure drop across the reactor, subtracted from the outlet '
                           'pressure.'}],
 'ComponentSplitter': [{'name': 'splits',
                        'label': 'Component split fractions',
                        'type': 'json',
                        'complex': True,
                        'help': 'Dictionary mapping component_id to fraction sent to overhead '
                                'outlet; values must be in [0, 1]. Omitted components use '
                                'default_split.'},
                       {'name': 'default_split',
                        'label': 'Default split fraction to overhead',
                        'type': 'number',
                        'default': 0,
                        'min': 0,
                        'max': 1,
                        'help': 'Fraction to overhead for components not explicitly listed in '
                                'splits; must be in [0, 1].'},
                       {'name': 'T_overhead',
                        'label': 'Overhead outlet temperature',
                        'type': 'number',
                        'unit': 'K',
                        'dim': 'temperature',
                        'help': 'Temperature of overhead outlet stream; defaults to inlet '
                                'temperature if not specified.'},
                       {'name': 'T_bottoms',
                        'label': 'Bottoms outlet temperature',
                        'type': 'number',
                        'unit': 'K',
                        'dim': 'temperature',
                        'help': 'Temperature of bottoms outlet stream; defaults to inlet '
                                'temperature if not specified.'},
                       {'name': 'P_overhead',
                        'label': 'Overhead outlet pressure',
                        'type': 'number',
                        'unit': 'Pa',
                        'dim': 'pressure',
                        'help': 'Pressure of overhead outlet stream; defaults to inlet pressure '
                                'if not specified.'},
                       {'name': 'P_bottoms',
                        'label': 'Bottoms outlet pressure',
                        'type': 'number',
                        'unit': 'Pa',
                        'dim': 'pressure',
                        'help': 'Pressure of bottoms outlet stream; defaults to inlet pressure '
                                'if not specified.'}],
 'Compressor': [{'name': 'P_out',
                 'label': 'Outlet pressure',
                 'type': 'number',
                 'required': True,
                 'unit': 'Pa',
                 'dim': 'pressure',
                 'help': 'Compressor outlet pressure; must exceed inlet pressure'},
                {'name': 'eta',
                 'label': 'Isentropic efficiency',
                 'type': 'number',
                 'default': 0.75,
                 'min': 0,
                 'max': 1,
                 'help': 'Isentropic efficiency; ideal path is isentropic to P_out, actual '
                         'enthalpy rise is ideal rise divided by eta'}],
 'ConversionReactor': [{'name': 'reaction',
                        'label': 'Single reaction specification',
                        'type': 'json',
                        'complex': True,
                        'editor': 'reaction',
                        'editor_opts': {'kind': 'stoichiometric', 'multiple': True,
                                        'conversion': True, 'key_required': True},
                        'help': 'Dict with stoich (component: coefficient) and key (limiting '
                                'reactant id); used when single reaction'},
                       {'name': 'conversion',
                        'label': 'Conversion of key reactant',
                        'type': 'number',
                        'min': 0,
                        'max': 1,
                        'help': "Fractional conversion (0..1) for the reaction's key reactant; "
                                'applies in single form only'},
                       {'name': 'reactions',
                        'label': 'Multiple reaction specifications',
                        'type': 'json',
                        'complex': True,
                        'editor': 'reaction',
                        'editor_opts': {'kind': 'stoichiometric', 'multiple': True,
                                        'conversion': True, 'key_required': True},
                        'help': 'Array of reaction dicts, each with stoich, key, and conversion; '
                                'used when multiple reactions'},
                       {'name': 'dP',
                        'label': 'Pressure drop',
                        'type': 'number',
                        'default': 0,
                        'unit': 'Pa',
                        'dim': 'pressure',
                        'min': 0,
                        'help': 'Absolute pressure drop (Pa) across reactor; defaults to 0 if '
                                'omitted'},
                       {'name': 'T_out',
                        'label': 'Outlet temperature',
                        'type': 'number',
                        'unit': 'K',
                        'dim': 'temperature',
                        'help': 'Outlet temperature (K) for isothermal operation; if absent, '
                                'reactor is adiabatic (temperature sets via energy balance)'}],
 'Cyclone': [{'name': 'solids',
              'label': 'Solid component(s)',
              'type': 'string',
              'required': True,
              'help': 'The dust component id (str) or list of component ids to be separated; '
                      'required.'},
             {'name': 'psd',
              'label': 'Particle size distribution',
              'type': 'json',
              'required': True,
              'unit': 'microns/fraction',
              'complex': True,
              'help': 'List of {"d_microns": diameter_microns, "mass_frac": fraction} bins; '
                      'required, non-empty, mass_frac sum to 1±2%.'},
             {'name': 'particle_density',
              'label': 'Particle density',
              'type': 'number',
              'required': True,
              'unit': 'kg/m³',
              'min': 0,
              'help': 'Density of the solid particles (kg/m³), required; Lapple d50 scales with '
                      'rho_p.'},
             {'name': 'geometry',
              'label': 'Geometry family',
              'type': 'select',
              'default': 'Lapple',
              'options': ['Lapple', 'Stairmand_HE', 'Stairmand_HT'],
              'help': "Standard cyclone proportion ratios; default 'Lapple'."},
             {'name': 'body_diameter',
              'label': 'Body diameter',
              'type': 'number',
              'unit': 'm',
              'min': 0,
              'help': 'Explicit cyclone body diameter (m); provide this OR inlet_velocity, not '
                      'both.'},
             {'name': 'inlet_velocity',
              'label': 'Design inlet velocity',
              'type': 'number',
              'unit': 'm/s',
              'min': 0,
              'help': 'Target inlet velocity (m/s) to size body_diameter; classic range 15–27 '
                      'm/s, ~18 m/s optimum; provide this OR body_diameter, not both.'},
             {'name': 'n_cyclones',
              'label': 'Number of parallel cyclones',
              'type': 'int',
              'default': 1,
              'min': 1,
              'help': 'Count of identical parallel cyclones sharing the inlet flow; default 1.'}],
 'Decanter': [{'name': 'T',
               'label': 'Decanter temperature',
               'type': 'number',
               'required': True,
               'unit': 'K',
               'dim': 'temperature',
               'min': 273.15,
               'help': 'Decanter temperature for the PT three-phase flash; required — adiabatic '
                       '(PH) flashes not supported.'},
              {'name': 'P',
               'label': 'Decanter pressure',
               'type': 'number',
               'unit': 'Pa',
               'dim': 'pressure',
               'min': 0,
               'help': 'Decanter pressure; defaults to inlet stream pressure if omitted.'},
              {'name': 'reflux_layer',
               'label': 'Reflux layer',
               'type': 'select',
               'default': 'light',
               'options': ['light', 'heavy'],
               'help': 'Which settled layer (light/organic or heavy/aqueous) feeds the reflux '
                       'split; ignored if reflux_fraction is 0 or absent.'},
              {'name': 'reflux_fraction',
               'label': 'Reflux fraction',
               'type': 'number',
               'default': 0,
               'min': 0,
               'max': 1,
               'help': 'Fraction of the reflux_layer returned on the reflux port (0–1); '
                       'remainder leaves on product port; omit or 0 to split neither layer.'}],
 'EquilibriumReactor': [{'name': 'reaction',
                         'label': 'Reaction definition',
                         'type': 'json',
                         'complex': True,
                         'editor': 'reaction',
                         'editor_opts': {'kind': 'stoichiometric', 'multiple': False,
                                         'conversion': False, 'key_required': False},
                         'help': 'Single reaction stoichiometry: {stoich: {component: '
                                 "coefficient}, key?: limiting_reactant}. Either 'reaction' or "
                                 "'reactions' must be present."},
                        {'name': 'reactions',
                         'label': 'Reaction list',
                         'type': 'json',
                         'complex': True,
                         'editor': 'reaction',
                         'editor_opts': {'kind': 'stoichiometric', 'multiple': False,
                                         'conversion': False, 'key_required': False},
                         'help': "Array of reaction dicts; the first is used. Either 'reaction' "
                                 "or 'reactions' must be present."},
                        {'name': 'T',
                         'label': 'Reactor temperature',
                         'type': 'number',
                         'required': True,
                         'unit': 'K',
                         'dim': 'temperature',
                         'help': 'Isothermal reactor temperature; K_eq is evaluated here to '
                                 'solve for equilibrium extent.'},
                        {'name': 'dP',
                         'label': 'Pressure drop',
                         'type': 'number',
                         'default': 0,
                         'unit': 'Pa',
                         'dim': 'pressure',
                         'min': 0,
                         'help': 'Pressure drop from inlet to outlet.'}],
 'Evaporator': [{'name': 'P',
                 'label': 'Operating Pressure',
                 'type': 'number',
                 'unit': 'Pa',
                 'dim': 'pressure',
                 'min': 1,
                 'help': 'Evaporator operating pressure. Defaults to inlet pressure if not '
                         'specified.'},
                {'name': 'T',
                 'label': 'Outlet Temperature',
                 'type': 'number',
                 'unit': 'K',
                 'dim': 'temperature',
                 'min': 273.15,
                 'help': 'Outlet temperature for PT flash. Exactly one of T, duty, or '
                         'vapor_fraction must be specified.'},
                {'name': 'duty',
                 'label': 'Heat Input Duty',
                 'type': 'number',
                 'unit': 'W',
                 'dim': 'power',
                 'help': 'Heat input (W) for PH flash. Exactly one of T, duty, or vapor_fraction '
                         'must be specified.'},
                {'name': 'vapor_fraction',
                 'label': 'Vapor Mole Fraction',
                 'type': 'number',
                 'min': 0,
                 'max': 1,
                 'help': 'Molar vapor fraction of combined outlet (0–1). For multicomponent '
                         'feeds solved by root-finding T; for pure fluids solved by enthalpy. '
                         'Exactly one of T, duty, or vapor_fraction must be specified.'}],
 'Expander': [{'name': 'P_out',
               'label': 'Outlet Pressure',
               'type': 'number',
               'required': True,
               'unit': 'Pa',
               'dim': 'pressure',
               'min': 0,
               'help': 'Outlet pressure; must be lower than inlet pressure for expansion'},
              {'name': 'eta',
               'label': 'Isentropic Efficiency',
               'type': 'number',
               'default': 0.8,
               'min': 0,
               'max': 1,
               'help': 'Isentropic efficiency; real enthalpy drop is ideal drop times eta, range '
                       '(0, 1]'}],
 'ExtractionColumn': [{'name': 'n_stages',
                       'label': 'Number of theoretical stages',
                       'type': 'int',
                       'required': True,
                       'min': 1,
                       'help': 'Number of theoretical stages in the counter-current '
                               'liquid-liquid extraction column; must be >= 1.'},
                      {'name': 'T',
                       'label': 'Operating temperature',
                       'type': 'number',
                       'required': True,
                       'unit': 'K',
                       'dim': 'temperature',
                       'min': 0,
                       'help': 'Isothermal stage temperature (required); the column operates at '
                               'a single fixed temperature.'},
                      {'name': 'P',
                       'label': 'Operating pressure',
                       'type': 'number',
                       'unit': 'Pa',
                       'dim': 'pressure',
                       'min': 0,
                       'help': 'Operating pressure; defaults to feed_in inlet pressure if not '
                               'specified.'},
                      {'name': 'max_iter',
                       'label': 'Maximum iterations',
                       'type': 'int',
                       'default': 300,
                       'min': 1,
                       'help': 'Maximum number of Gauss-Seidel sweeps before raising a '
                               'convergence error; default 300.'}],
 'FiredHeater': [{'name': 'efficiency',
                  'label': 'Fired efficiency',
                  'type': 'number',
                  'default': 0.85,
                  'min': 0,
                  'max': 1,
                  'help': 'LHV-basis fired efficiency (ratio of process duty to fuel duty); '
                          'typical 0.80-0.90 for modern process furnaces. Must be in (0, 1].'},
                 {'name': 'T_out',
                  'label': 'Outlet temperature',
                  'type': 'number',
                  'unit': 'K',
                  'dim': 'temperature',
                  'help': 'Outlet temperature setpoint. Specify exactly one of T_out or Q.'},
                 {'name': 'Q',
                  'label': 'Process duty',
                  'type': 'number',
                  'unit': 'W',
                  'dim': 'power',
                  'min': 0,
                  'help': 'Fixed process absorbed duty (must be > 0 for heating). Specify '
                          'exactly one of T_out or Q.'},
                 {'name': 'dP',
                  'label': 'Pressure drop',
                  'type': 'number',
                  'default': 0,
                  'unit': 'Pa',
                  'dim': 'pressure',
                  'min': 0,
                  'help': 'Pressure drop across the heater tubes.'},
                 {'name': 'design_split',
                  'label': 'Enable radiant/convective design',
                  'type': 'boolean',
                  'help': 'Trigger the radiant/convective firebox design split (also triggered '
                          'by fuel, excess_air, or bridgewall_T).'},
                 {'name': 'fuel',
                  'label': 'Fuel composition',
                  'type': 'json',
                  'requires': {'design_split': True},
                  'complex': True,
                  'help': 'Fuel composition as a dict {component_id: mole_fraction} or a single '
                          'string component_id for pure fuel. Default is pure methane. Only '
                          'C/H/O fuels supported.'},
                 {'name': 'excess_air',
                  'label': 'Excess air fraction',
                  'type': 'number',
                  'default': 0.15,
                  'min': 0,
                  'requires': {'design_split': True},
                  'help': 'Combustion excess air as a fraction of stoichiometric (0.15 = 15% '
                          'excess). Default 0.15.'},
                 {'name': 'fuel_T',
                  'label': 'Fuel inlet temperature',
                  'type': 'number',
                  'default': 298.15,
                  'unit': 'K',
                  'dim': 'temperature',
                  'requires': {'design_split': True},
                  'help': 'Inlet temperature of the fuel gas. Default 298.15 K (25 C).'},
                 {'name': 'air_T',
                  'label': 'Combustion air inlet temperature',
                  'type': 'number',
                  'default': 298.15,
                  'unit': 'K',
                  'dim': 'temperature',
                  'requires': {'design_split': True},
                  'help': 'Inlet temperature of the combustion air. Default 298.15 K (25 C).'},
                 {'name': 'bridgewall_T',
                  'label': 'Bridgewall (firebox-exit) temperature',
                  'type': 'number',
                  'unit': 'K',
                  'dim': 'temperature',
                  'requires': {'design_split': True},
                  'help': 'Flue gas temperature leaving the firebox (entering convective bank). '
                          'Sets the radiant/convective split. If omitted, defaults to min(1150 '
                          'K, 0.5*(T_adiabatic+T_out)). Must be between T_out and T_adiabatic.'},
                 {'name': 'loss_fraction',
                  'label': 'Casing/radiation loss fraction',
                  'type': 'number',
                  'default': 0.015,
                  'min': 0,
                  'max': 1,
                  'requires': {'design_split': True},
                  'help': 'Fraction of available heat lost via casing radiation/conduction. '
                          'Default 0.015 (1.5%, typical per Towler & Sinnott).'},
                 {'name': 'radiant_flux',
                  'label': 'Radiant section design flux',
                  'type': 'number',
                  'default': 32000,
                  'unit': 'W/m^2',
                  'dim': 'power',
                  'min': 0,
                  'requires': {'design_split': True},
                  'help': 'Design radiant heat flux (cold-plane tube surface). Default 32 kW/m^2 '
                          '(Perry/Towler typical: 25-40 kW/m^2).'},
                 {'name': 'convective_U',
                  'label': 'Convective bank overall heat transfer coefficient',
                  'type': 'number',
                  'default': 40,
                  'unit': 'W/m^2K',
                  'dim': 'UA',
                  'min': 0,
                  'requires': {'design_split': True},
                  'help': 'Overall U for the convective bank (gas-side dominated). Default 40 '
                          'W/m^2K (typical 20-60 W/m^2K).'}],
 'Flash': [{'name': 'P',
            'label': 'Outlet pressure',
            'type': 'number',
            'unit': 'Pa',
            'dim': 'pressure',
            'help': 'Pressure at the flash drum outlet; defaults to inlet pressure if omitted.'},
           {'name': 'T',
            'label': 'Outlet temperature',
            'type': 'number',
            'unit': 'K',
            'dim': 'temperature',
            'help': 'Temperature for isothermal operation (PT flash); omit for adiabatic (PH) '
                    'flash.'}],
 'GibbsReactor': [{'name': 'T',
                   'label': 'Outlet temperature',
                   'type': 'number',
                   'required': True,
                   'unit': 'K',
                   'dim': 'temperature',
                   'help': 'Temperature at which the Gibbs equilibrium is evaluated (also the '
                           'outlet temperature). The unit holds the outlet at this temperature '
                           'via reported duty.'},
                  {'name': 'P',
                   'label': 'Outlet pressure',
                   'type': 'number',
                   'unit': 'Pa',
                   'dim': 'pressure',
                   'min': 0,
                   'help': 'Outlet pressure. If omitted, defaults to the inlet stream pressure. '
                           'Must be positive.'},
                  {'name': 'dP',
                   'label': 'Pressure drop',
                   'type': 'number',
                   'default': 0,
                   'unit': 'Pa',
                   'dim': 'pressure',
                   'min': 0,
                   'help': 'Pressure drop across the reactor, subtracted from the outlet '
                           'pressure. Defaults to zero (no pressure drop).'}],
 'HeatExchanger': [{'name': 'duty',
                    'label': 'Heat duty (hot→cold)',
                    'type': 'number',
                    'unit': 'W',
                    'dim': 'power',
                    'help': 'Heat transferred from hot stream to cold stream; exactly one of '
                            'duty/T_hot_out/T_cold_out/UA must be specified'},
                   {'name': 'T_hot_out',
                    'label': 'Hot outlet temperature',
                    'type': 'number',
                    'unit': 'K',
                    'dim': 'temperature',
                    'help': 'Target temperature of hot stream outlet; exactly one of '
                            'duty/T_hot_out/T_cold_out/UA must be specified'},
                   {'name': 'T_cold_out',
                    'label': 'Cold outlet temperature',
                    'type': 'number',
                    'unit': 'K',
                    'dim': 'temperature',
                    'help': 'Target temperature of cold stream outlet; exactly one of '
                            'duty/T_hot_out/T_cold_out/UA must be specified'},
                   {'name': 'UA',
                    'label': 'Heat exchanger conductance',
                    'type': 'number',
                    'unit': 'W/K',
                    'dim': 'UA',
                    'min': 0,
                    'help': 'Thermal conductance; used with effectiveness-NTU method; exactly '
                            'one of duty/T_hot_out/T_cold_out/UA must be specified'},
                   {'name': 'dP_hot',
                    'label': 'Hot side pressure drop',
                    'type': 'number',
                    'default': 0,
                    'unit': 'Pa',
                    'dim': 'pressure',
                    'min': 0,
                    'help': 'Pressure drop on hot stream side'},
                   {'name': 'dP_cold',
                    'label': 'Cold side pressure drop',
                    'type': 'number',
                    'default': 0,
                    'unit': 'Pa',
                    'dim': 'pressure',
                    'min': 0,
                    'help': 'Pressure drop on cold stream side'},
                   {'name': 'arrangement',
                    'label': 'Heat exchanger arrangement',
                    'type': 'select',
                    'default': 'counterflow',
                    'options': ['counterflow', 'cocurrent'],
                    'help': 'Flow arrangement for effectiveness-NTU calculation (used only with '
                            'UA spec)'}],
 'Heater': [{'name': 'dP',
             'label': 'Pressure drop',
             'type': 'number',
             'default': 0,
             'unit': 'Pa',
             'dim': 'pressure',
             'min': 0,
             'help': 'Pressure drop across the heater/cooler unit'},
            {'name': 'T_out',
             'label': 'Outlet temperature',
             'type': 'number',
             'unit': 'K',
             'dim': 'temperature',
             'min': 0,
             'help': 'Target outlet temperature; mutually exclusive with Q'},
            {'name': 'Q',
             'label': 'Duty',
             'type': 'number',
             'unit': 'W',
             'dim': 'power',
             'help': 'Fixed heat duty (positive = heating, negative = cooling); mutually '
                     'exclusive with T_out'}],
 'Makeup': [{'name': 'component',
             'label': 'Make-up species',
             'type': 'string',
             'required': True,
             'help': 'The chemical species to maintain at target molar flow; must be in the '
                     'inlet stream.'},
            {'name': 'target',
             'label': 'Target outlet molar flow',
             'type': 'number',
             'required': True,
             'unit': 'mol/s',
             'dim': 'molar_flow',
             'min': 0,
             'help': 'Desired outlet molar flow of the component in mol/s; must be >= 0. If '
                     'inlet already exceeds target, no make-up is added.'},
            {'name': 'T',
             'label': 'Make-up temperature',
             'type': 'number',
             'unit': 'K',
             'dim': 'temperature',
             'help': 'Temperature of the injected pure make-up in Kelvin; defaults to inlet '
                     'temperature.'},
            {'name': 'P',
             'label': 'Make-up pressure',
             'type': 'number',
             'unit': 'Pa',
             'dim': 'pressure',
             'help': 'Pressure of the injected pure make-up in Pa; defaults to inlet pressure.'}],
 'Mixer': [{'name': 'dP',
            'label': 'Outlet pressure drop',
            'type': 'number',
            'default': 0,
            'unit': 'Pa',
            'dim': 'pressure',
            'min': 0,
            'help': 'Pressure drop from lowest inlet to outlet; outlet P = min(inlet P) - dP.'}],
 'MultiStreamExchanger': [{'name': 'passes',
                           'label': 'Pass specifications',
                           'type': 'json',
                           'required': True,
                           'complex': True,
                           'help': 'List of pass-spec dicts (at least 2 passes); each has inlet '
                                   'port, optional T_out or duty, optional dP.'},
                          {'name': 'heat_loss',
                           'label': 'Heat loss',
                           'type': 'number',
                           'default': 0,
                           'unit': 'W',
                           'dim': 'power',
                           'help': 'Unwanted heat loss through the core walls (W); positive '
                                   'loss, deducted from energy balance.'},
                          {'name': 'min_approach',
                           'label': 'Minimum internal temperature approach (MITA)',
                           'type': 'number',
                           'unit': 'K',
                           'dim': 'temperature',
                           'min': 0,
                           'help': 'Target minimum temperature difference (K) between hot and '
                                   'cold composite curves; global constraint that frees two '
                                   'passes.'},
                          {'name': 'ua',
                           'label': 'Conductance (UA)',
                           'type': 'number',
                           'unit': 'W/K',
                           'dim': 'UA',
                           'min': 0,
                           'help': 'Target overall conductance ΣΔQ/ΔT_lm (W/K); global '
                                   'constraint that frees two passes; mutually exclusive with '
                                   'min_approach.'}],
 'PFR': [{'name': 'V',
          'label': 'Reactor volume',
          'type': 'number',
          'required': True,
          'unit': 'm³',
          'min': 0,
          'help': 'Reactor volume in m³; must be positive.'},
         {'name': 'reactions',
          'label': 'Kinetic reactions',
          'type': 'json',
          'required': True,
          'complex': True,
          'editor': 'reaction',
          'editor_opts': {'kind': 'kinetic', 'multiple': True,
                          'conversion': False, 'key_required': True,
                          'reversible': True},
          'help': 'List of kinetic reaction dicts; each must have stoich (component:coefficient '
                  'map), key (limiting reactant), k0 (pre-exponential factor), Ea (activation '
                  'energy J/mol), and optional orders/k0_rev/Ea_rev for reversible reactions.'},
         {'name': 'T',
          'label': 'Isothermal temperature',
          'type': 'number',
          'unit': 'K',
          'dim': 'temperature',
          'min': 0,
          'help': 'Isothermal outlet temperature in K; if absent, reactor is adiabatic (T from '
                  'enthalpy conservation).'},
         {'name': 'n_steps',
          'label': 'Integration steps',
          'type': 'int',
          'default': 50,
          'min': 1,
          'help': 'Caps the integrator step at V/n_steps for resolution control; higher values '
                  'increase integration accuracy.'},
         {'name': 'dP',
          'label': 'Pressure drop',
          'type': 'number',
          'default': 0,
          'unit': 'Pa',
          'dim': 'pressure',
          'min': 0,
          'help': 'Single outlet pressure drop in Pa; kinetics evaluated at outlet pressure '
                  '(P_in - dP).'}],
 'PipeSegment': [{'name': 'length',
                  'label': 'Pipe length',
                  'type': 'number',
                  'required': True,
                  'unit': 'm',
                  'min': 0,
                  'help': 'Length of pipe in meters; must be positive'},
                 {'name': 'diameter',
                  'label': 'Inner pipe diameter',
                  'type': 'number',
                  'required': True,
                  'unit': 'm',
                  'min': 0,
                  'help': 'Inner diameter of pipe in meters; must be positive'},
                 {'name': 'roughness',
                  'label': 'Absolute pipe roughness',
                  'type': 'number',
                  'default': 4.5e-05,
                  'unit': 'm',
                  'min': 0,
                  'help': 'Absolute roughness of pipe wall in meters (default 4.5e-5 m for '
                          'commercial steel); used in Churchill correlation'},
                 {'name': 'elevation_change',
                  'label': 'Elevation change',
                  'type': 'number',
                  'default': 0,
                  'unit': 'm',
                  'help': 'Outlet height minus inlet height in meters; positive when outlet is '
                          'higher; contributes to hydrostatic pressure gradient'},
                 {'name': 'fittings_K',
                  'label': 'Minor loss coefficient',
                  'type': 'number',
                  'default': 0,
                  'min': 0,
                  'help': 'Sum of Crane TP-410 K factors for elbows, valves, and other fittings; '
                          'dimensionless loss coefficient applied to dynamic pressure'},
                 {'name': 'segments',
                  'label': 'Number of marching segments',
                  'type': 'int',
                  'default': 10,
                  'min': 1,
                  'help': 'Number of increments for stepping down the pipe; higher values give '
                          'finer pressure profile and account for density/velocity changes as '
                          'pressure drops'}],
 'Pump': [{'name': 'P_out',
           'label': 'Outlet pressure',
           'type': 'number',
           'required': True,
           'unit': 'Pa',
           'dim': 'pressure',
           'help': 'Discharge pressure (must exceed inlet pressure)'},
          {'name': 'eta',
           'label': 'Isentropic efficiency',
           'type': 'number',
           'default': 0.75,
           'min': 0,
           'max': 1,
           'help': 'Pump isentropic efficiency (fraction)'}],
 'ReboiledAbsorber': [{'name': 'n_stages',
                       'label': 'Number of theoretical stages',
                       'type': 'int',
                       'required': True,
                       'min': 2,
                       'help': 'Theoretical stages including the reboiler as stage n_stages. '
                               'Must be >= 2 (HYSYS reboiled-absorber with N stages + reboiler = '
                               'n_stages N+1 here).'},
                      {'name': 'feed_stage',
                       'label': 'Liquid feed stage',
                       'type': 'int',
                       'default': 1,
                       'min': 1,
                       'help': 'Stage number where the liquid feed enters (1=top, '
                               'n_stages-1=above reboiler).'},
                      {'name': 'vapor_rate',
                       'label': 'Overhead vapor rate specification',
                       'type': 'number',
                       'unit': 'mol/s',
                       'dim': 'molar_flow',
                       'min': 0,
                       'help': 'Overhead vapor rate (mol/s). Specify exactly one of vapor_rate, '
                               'boilup_ratio, or reboiler_duty. Must be strictly between 0 and '
                               'feed rate.'},
                      {'name': 'boilup_ratio',
                       'label': 'Boilup ratio specification',
                       'type': 'number',
                       'min': 0,
                       'help': 'Boilup ratio: V_reboiler / L_bottoms. Specify exactly one of '
                               'vapor_rate, boilup_ratio, or reboiler_duty. Closed by outer '
                               'Brent iteration on overhead vapor rate.'},
                      {'name': 'reboiler_duty',
                       'label': 'Reboiler heat duty',
                       'type': 'number',
                       'unit': 'W',
                       'dim': 'power',
                       'min': 0,
                       'help': 'Reboiler heat duty (W). Specify exactly one of vapor_rate, '
                               'boilup_ratio, or reboiler_duty. Closed by outer Brent iteration '
                               'on overhead vapor rate.'},
                      {'name': 'P',
                       'label': 'Top-stage pressure',
                       'type': 'number',
                       'unit': 'Pa',
                       'dim': 'pressure',
                       'min': 0,
                       'help': 'Top-stage (overhead) pressure in Pa. Defaults to feed inlet '
                               'pressure if not specified. Must be > 0.'},
                      {'name': 'P_bottom',
                       'label': 'Reboiler pressure',
                       'type': 'number',
                       'unit': 'Pa',
                       'dim': 'pressure',
                       'help': 'Reboiler (bottom stage) pressure in Pa. Creates a linear '
                               'pressure profile from P to P_bottom over n_stages. Cannot be '
                               'used with dP_stage.'},
                      {'name': 'dP_stage',
                       'label': 'Pressure rise per stage',
                       'type': 'number',
                       'default': 0,
                       'unit': 'Pa',
                       'dim': 'pressure',
                       'min': 0,
                       'help': 'Linear pressure rise per stage going down (Pa/stage). Default 0 '
                               '(uniform pressure). Cannot be used with P_bottom.'},
                      {'name': 'max_iter',
                       'label': 'Iteration limit',
                       'type': 'int',
                       'default': 120,
                       'min': 1,
                       'help': 'Maximum number of inner bubble-point iterations. Default 120.'}],
 'RigorousColumn': [{'name': 'n_stages',
                     'label': 'Total theoretical stages',
                     'type': 'int',
                     'required': True,
                     'min': 3,
                     'help': 'Number of theoretical stages including the condenser (stage 1) and '
                             'reboiler (stage n_stages); must be >= 3.'},
                    {'name': 'feed_stage',
                     'label': 'Feed stage (single feed)',
                     'type': 'int',
                     'min': 2,
                     'help': 'Stage number where the feed enters (2..n_stages-1 for reboiled, '
                             "2..n_stages for non-reboiled); mutually exclusive with 'feeds'."},
                    {'name': 'feeds',
                     'label': 'Multiple feed stages',
                     'type': 'json',
                     'complex': True,
                     'help': 'List of {"stage": j} dicts specifying where each inlet lands (in1, '
                             "in2, ...); mutually exclusive with 'feed_stage'."},
                    {'name': 'reflux_ratio',
                     'label': 'Reflux ratio',
                     'type': 'number',
                     'default': 1,
                     'min': 0,
                     'help': 'Molar reflux ratio L_1/D (heat removed by condenser / distillate). '
                             'Required for reboiled columns; optional for non-reboiled (seeds '
                             "initial traffic only; converged value is output in design['R'])."},
                    {'name': 'distillate_rate',
                     'label': 'Distillate molar rate',
                     'type': 'number',
                     'unit': 'mol/s',
                     'dim': 'molar_flow',
                     'min': 0,
                     'help': 'Distillate product rate in mol/s; mutually exclusive with '
                             "'distillate_to_feed'."},
                    {'name': 'distillate_to_feed',
                     'label': 'Distillate fraction of total feed',
                     'type': 'number',
                     'min': 0,
                     'max': 1,
                     'help': 'Distillate rate as a molar fraction of total feed (D/F); mutually '
                             "exclusive with 'distillate_rate'."},
                    {'name': 'P',
                     'label': 'Top-stage pressure',
                     'type': 'number',
                     'unit': 'Pa',
                     'dim': 'pressure',
                     'min': 0,
                     'help': 'Pressure at the condenser stage (Pa); defaults to the feed inlet '
                             'pressure.'},
                    {'name': 'dP_stage',
                     'label': 'Pressure rise per stage',
                     'type': 'number',
                     'default': 0,
                     'unit': 'Pa',
                     'dim': 'pressure',
                     'min': 0,
                     'help': 'Linear pressure increase going down the column, per stage (Pa); '
                             'defaults to 0 for uniform pressure.'},
                    {'name': 'partial_condenser',
                     'label': 'Partial condenser (vapor distillate)',
                     'type': 'boolean',
                     'default': False,
                     'help': 'If true, distillate leaves as vapor at dew point; if false '
                             '(default), distillate is liquid at bubble point (total '
                             'condenser).'},
                    {'name': 'max_iter',
                     'label': 'MESH iteration limit',
                     'type': 'int',
                     'default': 200,
                     'min': 1,
                     'help': 'Maximum number of MESH (Material, Equilibrium, Summation, Heat) '
                             'iterations before convergence is declared; default 200.'},
                    {'name': 'method',
                     'label': 'MESH update method',
                     'type': 'select',
                     'default': 'bubble_point',
                     'options': ['bubble_point', 'inside_out', 'naphtali_sandholm', 'sum_rates'],
                     'help': 'Algorithm for updating stage temperatures and vapor traffic: '
                             "'bubble_point' (Wang-Henke, narrow/medium-boiling), 'inside_out' "
                             "(Boston-Sullivan wide-boiling), 'naphtali_sandholm' "
                             "(simultaneous-correction, robust resid), 'sum_rates' "
                             '(Burningham-Otto, not recommended).'},
                    {'name': 'reboiled',
                     'label': 'Reboiled column',
                     'type': 'boolean',
                     'default': True,
                     'help': 'If true (default), the column has a reboiler on the bottom stage. '
                             'If false, the bottom stage is ordinary (no reboiler); feeds '
                             "stripping steam and requires method='bubble_point', 'inside_out', "
                             "or 'naphtali_sandholm'."},
                    {'name': 'side_draws',
                     'label': 'Side liquid/vapor draws',
                     'type': 'json',
                     'complex': True,
                     'help': 'List of {"stage": j, "phase": "liquid"|"vapor", "rate": mol/s} '
                             'dicts; draws remove saturated phase at exactly the given rate from '
                             'interior trays (2..n_stages-1).'},
                    {'name': 'stage_duties',
                     'label': 'Stage heat addition',
                     'type': 'json',
                     'unit': 'W',
                     'dim': 'power',
                     'complex': True,
                     'help': 'List of {"stage": j, "duty": W} dicts; heat added (negative = '
                             'removed) directly on interior trays (2..n_stages-1). Models '
                             'pumparound condensers. Requires reboiled=false.'},
                    {'name': 'decant_condenser',
                     'label': 'Integrated decanting condenser',
                     'type': 'boolean',
                     'default': False,
                     'help': 'If true, the condenser settles two liquid phases (heteroazeotropic '
                             "entrainer column); requires method='naphtali_sandholm' and "
                             "reboiled=true, and a 'condenser_T' is mandatory."},
                    {'name': 'condenser_T',
                     'label': 'Decant condenser temperature',
                     'type': 'number',
                     'unit': 'K',
                     'dim': 'temperature',
                     'min': 150,
                     'max': 1500,
                     'requires': {'decant_condenser': True},
                     'help': 'Temperature (K) at which the overhead vapor is condensed and the '
                             'two liquid phases are settled; required if decant_condenser=true.'},
                    {'name': 'reflux_layer',
                     'label': 'Reflux layer selection',
                     'type': 'select',
                     'default': 'organic',
                     'options': ['organic', 'light', 'aqueous', 'heavy'],
                     'requires': {'decant_condenser': True},
                     'help': "Which liquid layer is recycled as reflux: 'organic'/'light' "
                             "(default) or 'aqueous'/'heavy'. Used only if "
                             'decant_condenser=true.'},
                    {'name': 'reactions',
                     'label': 'Reactive distillation kinetics',
                     'type': 'json',
                     'complex': True,
                     'help': 'List of kinetic-reaction dicts {"stoich": {component: coeff}, '
                             '"key": limiting_reactant, "k0": mol/(m^3·s), "Ea": J/mol, '
                             '"orders": {component: order}, "k0_rev": (optional), "Ea_rev": '
                             '(optional), "orders_rev": (optional), "stages": [first, last]} '
                             "(1-based inclusive range). Requires method='bubble_point' and "
                             'reboiled=true.'},
                    {'name': 'tray_holdup',
                     'label': 'Per-stage liquid holdup volume',
                     'type': 'number',
                     'default': 1,
                     'unit': 'm^3',
                     'min': 0,
                     'help': 'Liquid holdup volume (m^3) on each reactive stage; default 1.0. '
                             'Used to convert kinetic rate (mol/(m^3·s)) to extent (mol/s). '
                             "Required if 'reactions' is provided."}],
 'RotaryVacuumFilter': [{'name': 'solids',
                         'label': 'Solid component(s)',
                         'type': 'string',
                         'required': True,
                         'help': 'Component id (string) or list of ids of the solid(s) to filter '
                                 'and separate into the cake.'},
                        {'name': 'psd',
                         'label': 'Particle size distribution',
                         'type': 'json',
                         'required': True,
                         'complex': True,
                         'help': 'Non-empty list of {"d_microns": diameter, "mass_frac": mass '
                                 'fraction} bins; mass fractions must sum to 1 (±2%).'},
                        {'name': 'pressure_drop',
                         'label': 'Pressure drop across cake',
                         'type': 'number',
                         'required': True,
                         'unit': 'Pa',
                         'dim': 'pressure',
                         'min': 0,
                         'help': 'Constant pressure driving force across the cake (Pa); must be '
                                 'positive and less than inlet pressure.'},
                        {'name': 'cycle_time_s',
                         'label': 'Drum cycle time',
                         'type': 'number',
                         'required': True,
                         'unit': 's',
                         'min': 0,
                         'help': 'Duration of one complete drum revolution (s).'},
                        {'name': 'alpha',
                         'label': 'Specific cake resistance',
                         'type': 'number',
                         'required': True,
                         'unit': 'm/kg',
                         'min': 0,
                         'help': 'Specific cake resistance (m/kg); no default exists; typical '
                                 "incompressible CaCO3 ~1e10–1e12 m/kg (Perry's 8e sec. 18)."},
                        {'name': 'solids_capture',
                         'label': 'Solids capture efficiency',
                         'type': 'number',
                         'default': 1,
                         'min': 0,
                         'max': 1,
                         'help': 'Fraction of solid component molar flow that reports to the '
                                 'cake; (0, 1]. Default 1.0 (complete capture, HYSYS '
                                 'assumption).'},
                        {'name': 'cake_moisture',
                         'label': 'Cake wet-basis moisture',
                         'type': 'number',
                         'default': 0.5,
                         'min': 0,
                         'max': 1,
                         'help': 'Liquid mass fraction of the wet cake (wet-basis); [0, 1). '
                                 'Default 0.5 (50% moisture, Hameed sec. 12.2 / McCabe 7e '
                                 'example).'},
                        {'name': 'submergence',
                         'label': 'Drum submergence fraction',
                         'type': 'number',
                         'default': 0.2,
                         'min': 0,
                         'max': 1,
                         'help': 'Fraction of the cycle during which the drum is submerged in '
                                 'the slurry; (0, 1). Default 0.20 (20%, Hameed sec. 12.2); '
                                 'McCabe uses 0.30.'},
                        {'name': 'filtrate_viscosity',
                         'label': 'Filtrate viscosity override',
                         'type': 'number',
                         'unit': 'Pa·s',
                         'min': 0,
                         'help': 'Override the databank viscosity (Pa·s) for the filtrate; if '
                                 'omitted, computed from the carrier-liquid properties at inlet '
                                 'T, P.'},
                        {'name': 'drum_radius_m',
                         'label': 'Drum radius (optional sizing hint)',
                         'type': 'number',
                         'unit': 'm',
                         'min': 0,
                         'help': 'Specify the drum radius (m) to report the suggested drum width '
                                 '(area = 2πRW); if omitted, a square drum (W = 2R) is '
                                 'assumed.'}],
 'Saturator': [{'name': 'saturant',
                'label': 'Saturant component',
                'type': 'string',
                'default': 'water',
                'help': "Component name (e.g. 'water') to use as the condensable saturant. Must "
                        'be in the gas inlet composition.'},
               {'name': 'relative_humidity',
                'label': 'Target relative humidity',
                'type': 'number',
                'default': 1,
                'min': 0,
                'max': 1,
                'help': 'Fraction of saturation vapor mole fraction to achieve (0 < RH ≤ 1). 1.0 '
                        '= saturated; <1.0 = undersaturated.'},
               {'name': 'T',
                'label': 'Outlet temperature',
                'type': 'number',
                'unit': 'K',
                'dim': 'temperature',
                'help': 'Isothermal operating temperature (K). Defaults to the gas inlet '
                        'temperature.'},
               {'name': 'P',
                'label': 'Outlet pressure',
                'type': 'number',
                'unit': 'Pa',
                'dim': 'pressure',
                'help': 'Operating pressure (Pa). Defaults to the gas inlet pressure.'},
               {'name': 'dP',
                'label': 'Pressure drop',
                'type': 'number',
                'default': 0,
                'unit': 'Pa',
                'dim': 'pressure',
                'help': 'Pressure drop (Pa) across the saturator (subtracted from P to compute '
                        'outlet pressure).'}],
 'ShortcutColumn': [{'name': 'light_key',
                     'label': 'Light key component',
                     'type': 'string',
                     'required': True,
                     'help': 'Component ID of the light key (most volatile of the key pair); '
                             'must be in feed.'},
                    {'name': 'heavy_key',
                     'label': 'Heavy key component',
                     'type': 'string',
                     'required': True,
                     'help': 'Component ID of the heavy key (least volatile of the key pair); '
                             'must be in feed and different from light_key.'},
                    {'name': 'recovery_light',
                     'label': 'Light key recovery',
                     'type': 'number',
                     'default': 0.99,
                     'min': 0,
                     'max': 1,
                     'help': 'Fraction of light key recovered to distillate (0 < x < 1); default '
                             '0.99.'},
                    {'name': 'recovery_heavy',
                     'label': 'Heavy key recovery',
                     'type': 'number',
                     'default': 0.99,
                     'min': 0,
                     'max': 1,
                     'help': 'Fraction of heavy key recovered to bottoms (0 < x < 1); default '
                             '0.99.'},
                    {'name': 'rr_factor',
                     'label': 'Reflux ratio multiplier',
                     'type': 'number',
                     'default': 1.3,
                     'min': 1,
                     'help': 'Operating reflux ratio as a multiple of minimum (R/R_min); must be '
                             '> 1; default 1.3.'},
                    {'name': 'P',
                     'label': 'Column pressure',
                     'type': 'number',
                     'unit': 'Pa',
                     'dim': 'pressure',
                     'min': 0,
                     'help': 'Column pressure in Pa; defaults to inlet stream pressure if absent '
                             'or zero.'},
                    {'name': 'partial_condenser',
                     'label': 'Use partial condenser',
                     'type': 'boolean',
                     'default': False,
                     'help': 'If true, distillate leaves as vapor at dew point; if false '
                             '(default), as liquid at bubble point (total condenser).'}],
 'Source': [{'name': 'molar_flow',
             'label': 'Molar flow rate',
             'type': 'number',
             'required': True,
             'unit': 'mol/s',
             'dim': 'molar_flow',
             'min': 0,
             'help': 'Total molar flow of the source stream'},
            {'name': 'T',
             'label': 'Temperature',
             'type': 'number',
             'required': True,
             'unit': 'K',
             'dim': 'temperature',
             'min': 0,
             'help': 'Temperature of the source stream'},
            {'name': 'P',
             'label': 'Pressure',
             'type': 'number',
             'required': True,
             'unit': 'Pa',
             'dim': 'pressure',
             'min': 0,
             'help': 'Pressure of the source stream'},
            {'name': 'z',
             'label': 'Composition',
             'type': 'json',
             'required': True,
             'complex': True,
             'help': 'Mole fraction composition as {component: mole_fraction}; automatically '
                     'normalized'}],
 'Splitter': [{'name': 'split',
               'label': 'Flow split fraction to out1',
               'type': 'number',
               'default': 0.5,
               'min': 0,
               'max': 1,
               'help': 'Fraction of inlet molar flow sent to out1; remainder goes to out2.'}],
 'SulfurCondenser': [{'name': 'T',
                      'label': 'Outlet temperature',
                      'type': 'number',
                      'required': True,
                      'unit': 'K',
                      'dim': 'temperature',
                      'min': 273.15,
                      'help': 'Condenser outlet temperature; required. Gas leaving is saturated '
                              'in elemental sulfur vapour at this T.'},
                     {'name': 'P',
                      'label': 'Outlet pressure',
                      'type': 'number',
                      'unit': 'Pa',
                      'dim': 'pressure',
                      'min': 0,
                      'help': 'Condenser outlet absolute pressure in Pa; defaults to inlet '
                              'pressure if omitted.'},
                     {'name': 'dP',
                      'label': 'Pressure drop',
                      'type': 'number',
                      'default': 0,
                      'unit': 'Pa',
                      'dim': 'pressure',
                      'min': 0,
                      'help': 'Pressure drop across the condenser in Pa (subtracted from outlet '
                              'pressure if P is also specified); defaults to zero.'}],
 'ThreePhaseSeparator': [{'name': 'T',
                          'label': 'Separator temperature',
                          'type': 'number',
                          'required': True,
                          'unit': 'K',
                          'dim': 'temperature',
                          'min': 273.15,
                          'help': 'Temperature at which the PT three-phase flash is performed; '
                                  'required (adiabatic PH mode deliberately unsupported to avoid '
                                  'mixing VL and VLN enthalpy surfaces).'},
                         {'name': 'P',
                          'label': 'Separator pressure',
                          'type': 'number',
                          'unit': 'Pa',
                          'dim': 'pressure',
                          'min': 0,
                          'help': 'Pressure at which the PT flash is performed; defaults to the '
                                  'inlet stream pressure if not specified.'}],
 'Valve': [{'name': 'P_out',
            'label': 'Outlet pressure',
            'type': 'number',
            'unit': 'Pa',
            'dim': 'pressure',
            'min': 0,
            'help': 'Target outlet pressure; if specified, overrides dP calculation'},
           {'name': 'dP',
            'label': 'Pressure drop',
            'type': 'number',
            'default': 0,
            'unit': 'Pa',
            'dim': 'pressure',
            'min': 0,
            'help': 'Pressure decrease (Pa); used only if P_out not specified; default 0.0'}]}
